### ISSUE TITLE
Event Roles template edits

### ISSUE THREAD

**Issue by selina-aragon** [softwaresaved/event-organisation-guide#69]
The Comms team has made edits to the Event Roles template. Please use this issue to track any comments or queries of the changes.

The edited template can be found in Google Drive:
https://docs.google.com/document/d/1bfwdm6BHGTCFDy8p0DWpz4mrtKnmum2h/edit?rtpof=true

**Comment by shoaibsufi** [comment]
![Screenshot 2020-12-02 at 10 19 16](https://user-images.githubusercontent.com/473827/100860058-e872d080-3487-11eb-9de1-79f426180005.png)

I started using the URL as links rather than link text for trust reasons - these are random documents for people coming across them so if they can see the link they will feel confident clicking on it - rather than any danger of a textual link not being what it appears. But you are right - we use linked text in other places so I will convert it back to those and leave the checking for the people using the document.

**Comment by shoaibsufi** [comment]
copy and changes at - https://docs.google.com/document/d/14lEszj4KXeU3Uuwd_M7EjVtrg-7P7hMn/edit#heading=h.gjdgxs
